# Generated by Django 3.1.7 on 2021-04-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210402_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='short_bio',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
